version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gt-sitio-web-staging
    image: gt-sitio-web-staging:0.1.0
    ports:
      - "5157:80"
    restart: unless-stopped